Areas/Admin/Controllers/StackController.cs
using Dapper.Contrib.Extensions;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using PagedList;
using QuanLyHoSo.Dao;
using QuanLyHoSo.Dao.DaoAdmin;
using QuanLyHoSo.Models;
using QuanLyHoSo.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyHoSo.Areas.Admin.Controllers
{
    [Authorize(Roles = "Ngan")]
    public class StackController : System.Web.Mvc.Controller
    {
        // GET: Admin/Stack
        public ActionResult Index()
        {
            ViewBag.listKho = from k in Stuff.GetAll<Kho>()
                              where k.TrangThai == 1
                              select new SelectListItem
                              {
                                  Text = k.TenKho,
                                  Value = k.ID.ToString(),
                              };
            return View();
        }

        public PartialViewResult Search(string keyword, int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSizeNumber = 3;
            if (keyword == null) keyword = "";

            var results = from n in StackDao.GetAllStack()
                          orderby n.ID descending
                          where n.TenNgan.Contains(keyword) && n.TrangThai != 10
                          select n;
            ViewBag.search = keyword;
            var model = results.ToPagedList(pageNumber, pageSizeNumber);
            return PartialView("StackTable", model);
        }

        public JsonResult View(long ID)
        {
            Ngan ngan = Stuff.GetByID<Ngan>(ID);
            return Json(new
            {
                data = ngan,
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Change(long ID, int state)
        {
            StackDao.ChangeStateByID(ID, state, Session["UserNameNV"].ToString());
            return Json(new
            {
                heading = "Thành công",
                status = "success",
                message = "Thay đổi trạng thái thành công!"
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Save(Ngan Ngan)
        {
            string UserNameNV = Session["UserNameNV"].ToString();
            if (Ngan.ID == 0)
            {
                //create new kho
                StackDao.CreateStorage(Ngan, UserNameNV);
                var nextStk = Stuff.GetAll<Ngan>().LastOrDefault();
                Ngan.DuongDan = Stuff.GetByID<Kho>(Ngan.IDKho).DuongDan+"-"+ nextStk.ID.ToString();
                StackDao.UpdateStackNoChange(Ngan, Ngan.ID);
            }
            else
            {
                //update kho
                var dmCha = Stuff.GetByID<Kho>(Ngan.IDKho);
                string newPath = dmCha.DuongDan + "-" + Ngan.ID.ToString();
                Ngan.DuongDan = newPath;
                StackDao.UpdateStackNoChange(Ngan, Ngan.ID);
            }
            return Json(new
            {
                heading = "Thành công",
                status = "success",
                message = "Lưu thành công!"
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Delete(long ID)
        {
            StackDao.DeleteUserByID(ID, Session["UserNameNV"].ToString());
            return Json(new
            {
                error = false,
                heading = "Thành công",
                status = "success",
                message = "Xóa bản ghi thành công!"
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteAll(List<int> checkboxs)
        {
            foreach (var id in checkboxs)
            {
                StackDao.DeleteUserByID(id, Session["UserNameNV"].ToString());
            }
            return Json(new
            {
                heading = "Thành công",
                status = "success",
                message = $"Xóa {checkboxs.Count} bản ghi thành công!"
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ExcelModal()
        {
            try
            {
                string pathFile = string.Empty;
                string fileName = "Stack.xlsx";
                string pathFolder = "/Assets/Excel/Stack";
                if (Request.Files.Count > 0)
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        //tao folder
                        Directory.CreateDirectory(Server.MapPath(pathFolder));
                        // tao duong dan path
                        pathFile = Path.Combine(Server.MapPath(pathFolder), fileName);
                        file.SaveAs(pathFile);
                    }
                }
                Session["pathFile"] = pathFile;
                var listNganExcel = Stuff.GetListExcel<ViewExcelNgan>(pathFile);
                var listKho = Stuff.GetAll<Kho>();
                ViewBag.listNganExcel = listNganExcel;
                ViewBag.listKho = listKho;
                return PartialView();
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    error = true,
                    heading = "Thất bại",
                    icon = "error",
                    message = $"{ex}"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Excel(FormCollection fc)
        {
            var checkbox = (fc["checkbox"]).Split(',');
            var account =
                   from ke in Stuff.GetListExcel<ViewExcelNgan>(Session["pathFile"].ToString())
                   where ke.TenNgan != null &&
                         ke.MaNgan != null &&
                         ke.MaKhoChua != null &&
                         ke.KichThuoc != 0
                   join k in Stuff.GetAll<Kho>()
                   on ke.MaKhoChua equals k.MaKho
                   select new Ngan
                   {
                       TenNgan = ke.TenNgan,
                       MaNgan = ke.MaNgan,
                       IDKho = k.ID,
                       DuongDan =k.DuongDan,
                       TrangThai = ke.TrangThai,
                       KichThuoc = ke.KichThuoc,
                       MoTa = ke.MoTa,
                       NgayTao = DateTime.Now.ToString(),
                       NguoiTao = Session["UserNameNV"].ToString(),
                   };
            account = account.ToList();
            long tk;
            int i = 0;
            foreach (var nv in account)
            {
                nv.TrangThai = Convert.ToByte(checkbox[i]);
                i++;
            }

            using (var db = new SqlConnection(ConnectString.Setup()))
            {
                tk = db.Insert(account);
            }
            var listFixPath = Stuff.GetList<Ngan>($"select top {tk} * from Ngan  order by id desc");
            foreach(var n in listFixPath)
            {
                    var newPath = n.DuongDan + "-" + n.ID.ToString();
                    Stuff.ExecuteSql("Update Ngan Set DuongDan =@newPath where ID =@ID", new { newPath = newPath, ID = n.ID });
            }
            return Json(new
            {
                heading = "Thành công",
                status = "success",
                message = $"Lưu {tk} bản ghi thành công!"
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DownloadExcel()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            string ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            using (var package = new ExcelPackage())
            {
                //A workbook must have at least on cell, so lets add one... 
                var wsData = package.Workbook.Worksheets.Add("Data");
                var wsThongTinBang = package.Workbook.Worksheets.Add("ThongTinBang");

                //To set values in the spreadsheet use the Cells indexer.
                var dm = from k in Stuff.GetAll<Kho>()
                         where k.TrangThai !=10 && k.TrangThai!=100
                         select new
                         {
                             MaKHoChua = k.TenKho,
                             MaKhoCha = k.MaKho,
                         };

                var TrangThai = new List<State>() {
                    new State { TrangThai = "Đóng", MaTrangThai = 0  },
                    new State { TrangThai = "Mở", MaTrangThai = 1  },
                };
                var nd = new List<ViewExcelNgan>();
                wsData.Cells["A1"].LoadFromCollection(nd, true, TableStyles.Medium1);
                wsThongTinBang.Cells["A1"].LoadFromCollection(dm, true, TableStyles.Medium1);
                wsThongTinBang.Cells["D1"].LoadFromCollection(TrangThai, true, TableStyles.Medium1);


                var listDm = wsData.DataValidations.AddListValidation("C2");
                var listTrangThai = wsData.DataValidations.AddListValidation("D2");

                listDm.Formula.ExcelFormula = $"ThongTinBang!$B$2:$B${dm.Count() + 1}";
                listTrangThai.Formula.ExcelFormula = "ThongTinBang!$E$2:$E$3";


                wsData.Cells[1, 1, wsData.Dimension.End.Row, wsData.Dimension.End.Column].AutoFitColumns();
                wsThongTinBang.Cells[1, 1, wsThongTinBang.Dimension.End.Row, wsThongTinBang.Dimension.End.Column].AutoFitColumns();
                //Save the new workbook. We haven't specified the filename so use the Save as method.
                var excelData = package.GetAsByteArray();
                var fileName = "StackTemplate.xlsx";
                return File(excelData, ContentType, fileName);
            }
        }

    }
}

Areas/Admin/Views/Stack/ExcelModal.cshtml
@using System.Linq

@{
    var account =
    from ke in (List<QuanLyHoSo.ViewModel.ViewExcelNgan>)ViewBag.listNganExcel
    where ke.TenNgan != null &&
          ke.MaNgan != null &&
          ke.MaKhoChua != null &&
          ke.KichThuoc !=0
    join k in (List<QuanLyHoSo.Models.Kho>)ViewBag.listKho
    on ke.MaKhoChua equals k.MaKho
    select new
    {
        TenNgan = ke.TenNgan,
        MaNgan = ke.MaNgan,
        TenKhoChua = k.TenKho,
        TrangThai = ke.TrangThai,
        KichThuoc = ke.KichThuoc,
        MoTa = ke.MoTa

    };
}
<table class="table table-striped table-light table-bordered DisplayName w-100 table-hover">
    <tr>
        <th>
            Tên ngăn
        </th>
        <th>
            Mã ngăn
        </th>
        <th>
            Tên kho chứa
        </th>
        <th>
            Trạng thái
        </th>
        <th>
            Kích thước
        </th>
        <th>
            Mô tả
        </th>
    </tr>
    @foreach (var item in account)
    {
        <tr>
            <td>
                @item.TenNgan
            </td>
            <td>
                @item.MaNgan
            </td>
            <td>
                @item.TenKhoChua
            </td>
            @if (@item.TrangThai == 1)
            {
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input excelCheckbox" type="checkbox" checked>
                    </div>
                </td>
            }
            else
            {
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input excelCheckbox" type="checkbox">
                    </div>
                </td>
            }
            <td>
                @item.KichThuoc
            </td>
            <td>
                @item.MoTa
            </td>
        </tr>
    }
</table>

Areas/Admin/Views/Stack/Index.cshtml
@{

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<main>
    <!-- nav button start -->
    <section>
        <div class="container-fluid">

            <div class="btn-toolbar justify-content-between py-3" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group" role="group" aria-label="First group">
                    <button type="button" class="btn btn-outline-secondary disabled" onclick="GetCheckboxAll()" id="deleteAll">
                        <span>
                            <i class="fa-solid fa-trash-can"></i>

                        </span>
                        <span>Xóa tất cả</span>
                    </button>

                    <a href="/admin/Stack/DownloadExcel" class="btn btn-outline-secondary" target="_blank">
                        <span>
                            <i class="bi bi-cloud-arrow-down"></i>
                        </span>
                        <span>Tập tin mẫu</span>
                    </a>
                    <button type="button" class="btn btn-outline-secondary">
                        <input type="file" id="excelUpload" onchange=" ModalExcel()" name="excelUpload" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" class="custom-file-upload" />
                        <label for="excelUpload" class="custom-file-upload ">
                            <span>
                                <i class="bi bi-paperclip"></i>
                            </span>
                            <span>Thêm từ biểu mẫu</span>
                        </label>
                    </button>
                    <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" id="modal-on"
                            data-bs-target="#staticBackdrop">
                        <span>
                            <i class="bi bi-plus-circle-fill"></i>
                        </span>
                        <span>Thêm ngăn mới</span>
                    </button>
                </div>
                <div class="input-group">
                    <input type="text" name="name" value="" class="rounded border-1" id="searchInput" />
                    <button for="searchInput" id="searchBtn" class="btn btn-outline-secondary" onclick="SearchUser(event)">
                        <span>
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </span>
                        <span>Tìm kiếm</span>
                    </button>
                </div>
            </div>
        </div>
    </section>
    <!-- nav button end  -->
    <div id="tableContainer">
        <!-- table start -->
        @{
            Html.RenderAction("Search", "Stack", new { page = 1 });

        }
        <!-- table end -->
    </div>

    <!-- content start  -->
    <!-- content end  -->
</main>

<!-- modal start -->
<section>
    <div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg ">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title " id="exampleModalLabel">Thông tin tài khoản</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container" id="modalContainer">
                        <form action="" id="userForm">
                            <div class="row my-2">
                                <div class="col-12 fw-bold fst-italic">
                                    (*) Thông tin bắt buộc
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="TenNgan" class="form-label">Tên ngăn (*)</label>
                                        <input class="form-control" id="TenNgan" name="TenNgan">
                                    </div>
                                    <div class="form-group">
                                        <label for="MaNgan" class="form-label">Mã ngăn (*)</label>
                                        <input class="form-control" id="MaNgan" type="text" name="MaNgan">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group ">
                                        <label class="form-label " for="IDKho">Kho chứa ngăn (*)</label>

                                        @Html.DropDownList("IDKho", (IEnumerable<SelectListItem>)ViewBag.listKho, new { @class = "form-select" })
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label" for="TrangThai">Trạng thái (*)</label>
                                        <select class="form-select" id="TrangThai" name="TrangThai">
                                            <option value="0">Khóa</option>
                                            <option value="1">Mở</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="KichThuoc" class="form-label">Kích thước ngăn (*)</label>
                                        <input class="form-control" id="KichThuoc" type="number" name="KichThuoc">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="MoTa" class="form-label">Mô tả</label>
                                        <textarea class="form-control" id="MoTa" name="MoTa"
                                                  rows="5"></textarea>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="submit" form="userForm" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- modal end -->
<!-- modal start -->
<section>
    <div class="modal fade " id="ExcelModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-lg ">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title " id="exampleModalLabel">Thông tin tài khoản hợp lệ</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container" id="excelContainer">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                    <button type="button" onclick="UpExcel()" class="btn btn-primary">Lưu người dùng</button>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- modal end -->

<script src="~/Assets/Admin/js/stack.js"></script>

Areas/Admin/Views/Stack/StackTable.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<QuanLyHoSo.ViewModel.ViewNgan>
<div class="table-responsive container-fluid">
    <table class="table table-striped table-light table-bordered display w-100" id="users">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="checkAll" class="form-check-input" id="checkAll" />
                </th>
                <th>Tên ngăn</th>
                <th>Mã ngăn</th>
                <th>Kho chứa</th>
                <th>Trạng thái</th>
                <th>Kích thước</th>
                <th>Mô tả</th>
                <th>Ngày tạo</th>
                <th>Người tạo</th>
                <th>Ngày sửa</th>
                <th>Người sửa</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody id="table-body">
            <input type="number" name="hidden" value="0" style="display:none" id="HiddenID" />
            @foreach (var item in Model)
            {
        <tr data-id="@item.ID">
            <td>
                <input type="checkbox" class="form-check-input checkboxs" name="checkboxs" data-id="@item.ID" />
            </td>
            <td>@item.TenNgan</td>
            <td>@item.MaNgan</td>
            <td>@item.TenKho</td>
            @if (@item.TrangThai == 1)
            {
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="button-@item.ID" checked onchange="ChangeState(@item.ID)">
                    </div>
                </td>
            }
            else
            {
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="button-@item.ID" onchange="ChangeState(@item.ID)">
                    </div>
                </td>
            }
            <td>@item.KichThuoc</td>

            <td>@item.MoTa</td>

            <td>@item.NgayTao</td>
            <td>@item.NguoiTao</td>
            <td>@item.NgaySua</td>
            <td>@item.NguoiSua</td>
            <td>
                <div class="btn-group btn-group-sm" role="group" aria-label="Basic mixed styles example">
                    <button type="button" class="btn btn-outline-secondary" onclick="ViewUser(@item.ID,event)">
                        <span>Xem</span>
                    </button>
                    <button type="button" class="btn btn-outline-secondary" onclick="UpdateUser(@item.ID,event)">
                        <span>Sửa</span>
                    </button>
                    <button type="button" class="btn btn-outline-secondary" onclick="DeleteUser(@item.ID,event)">
                        <span>Xóa</span>
                    </button>
                </div>
            </td>
        </tr>

            }
        </tbody>
    </table>
    <!-- Thêm phân trang vào -->
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    @Html.PagedListPager(Model,
    page => Url.Action("Search",
    new { keyword = ViewBag.search, page = page }),
PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "tableContainer" }))
    <!-- Kết thúc -->
</div>